server:
  port: 8081

spring:
  application:
    name: post-service
  cloud:
    aws:
      region:
        static: ap-northeast-2
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
  datasource:
    url: ${DB_URL}
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1000

server-uri: http://localhost:8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

aws:
  s3:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    bucketName: ${S3_BUCKET}
    region: ap-northeast-2
