server:
  port: 8081

spring:
  application:
    name: post-service
  cloud:
    aws:
      region:
        static: ap-northeast-2
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
  datasource:
    url: ENC(FcNHU/eL/6pkixUcn5Y5rSoV2nY7qFeF1MmMyBueSW1rH5+mI07xCmiNKCp8yfD4rtKpLuxD3M6wd86KqcVcnM+3zDOv0yddpVi9SgtZYiK8CF6l6Knu8QCGZKYs0B0T)
    username: admin
    password: ENC(3BPIozGn4dpefIL0XbYlMo15Y4L/QM30)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  elasticsearch:
    uris: http://210.109.81.201:9200
    connection-timeout: 1000

server-uri: http://61.109.236.137:8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://61.109.236.137:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

aws:
  s3:
    accessKey: ENC(cYzS3lv8ETCF6w3dxr6EbSWPJEDpbkkwIGpefNBm1LI=)
    secretKey: ENC(o7FqH8ixDcYs69rIu87fdcHPQ86fCxx7aAuk0jHLjB2jmtAlM9pkfuKdqfMhW5gwdxnSSiUsyns=)
    bucketName: ENC(x8uVDyRiXAUGIxS61MYoABMfPEKcxyCR)
    region: ap-northeast-2

review:
  ocr:
    base-url: http://central-01.tcp.tunnel.elice.io:50643/ocr
